#!/usr/bin/env bash

main() {
  source AppInfo.txt
  update_chart_version "$HELM_FULL_VERSION"
  git commit chart/ build AppInfo.txt -m "autocommit on $(date)" # && git push
  helm package charts/wordpress
  push_helm_chart "$APP_NAME" "$HELM_FULL_VERSION" "$REGISTRIES"
}

update_chart_version() {
  local version=$1
  if [[ -f charts/wordpress/Chart.yaml ]]; then
    sed -i.bak "s/^version: .*/version: ${version}/" charts/Chart.yaml
  else
    echo "Error: chart/Chart.yaml not found!" >&2
    exit 1
  fi
}

push_helm_chart() {
  local app_name="$1"
  local version="$2"
  local registries="$3"
  local chart_package="${app_name}-${version}.tgz"
  for registry in ${registries//,/ }; do
    if [[ -f "$chart_package" ]]; then
      helm push $chart_package "oci://$registry" && echo "Pushed Helm chart to ${registry}"
    else
      echo "Error: Chart package ${chart_package} not found!" >&2
    fi
  done
}


main

